[project]
name = "infisical-conf"
version = "0.1.0"
description = "Python configuration manager with local cache, wildcard operations, dirty-tracking backed by Infisical Secrets Management."
authors = [{ name = "Mark Traverse" }]
readme = "README-pypi.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

dependencies = [
    "infisicalsdk>=1.0.15",
    "requests>=2.31",
    "rich>=13.0.0"
]

[project.urls]
Homepage = "https://github.com/upstairs-at-erics/infisical-conf"
Repository = "https://github.com/upstairs-at-erics/infisical-conf"
Issues = "https://github.com/upstairs-at-erics/infisical-conf/issues"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
